version: '3.8'

services:

  nginx:
    image: nginx:1.15.0-alpine
    restart: always
    build:
      context: nginx
    networks:
      - node-network
    tty: true
    container_name: nginx
    ports: 
      - "8080:80"
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/user/source/app
    tty: true
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test:  "mysql -h 127.0.0.1 -uroot -proot nodedb -e 'select 1'"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge